# Generated by Django 5.0.3 on 2024-04-16 14:40

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_review_created_at_remove_review_updated_at_and_more'),
    ]

    operations = [
    ]
