# Generated by Django 5.0.3 on 2024-04-16 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_company_remove_movie_total_reviews_movie_company_and_more'),
    ]

    operations = [
    ]
