# Generated by Django 5.0.3 on 2024-04-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_company'),
    ]

    operations = [
    ]
